# Generated by Django 4.2.5 on 2025-05-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_signal_signalactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
